<!DOCTYPE html>
<html>
<head>
<title>ftn12_async_api.md</title>
<link rel="stylesheet" type="text/css" href="../../css/specs.css">
</head><body>
<pre>
FTN12: FutoIn Async API
Version: 1.11
Date: 2018-02-02
Copyright: 2014-2018 FutoIn Project (http://futoin.org)
Authors: Andrey Galkin
</pre>

<h1>CHANGES</h1>
<ul>
<li>v1.11 - 2018-02-02 - Andrey Galkin<ul>
<li>CHANGED: successStep() to be used for result injection</li>
<li>CHANGED: cosmetic fixes for API definition</li>
<li>NEW: Promise/await integration</li>
</ul>
</li>
<li>v1.10 - 2017-12-06 - Andrey Galkin<ul>
<li>NEW: added max queue length for <code>Mutex</code> and <code>Throttle</code></li>
<li>NEW: <code>Limiter</code> primitive</li>
</ul>
</li>
<li>v1.9 - 2017-11-17 - Andrey Galkin<ul>
<li>NEW: async_stack state variable</li>
<li>NEW: adding steps in error handler</li>
</ul>
</li>
<li>v1.8 - 2017-08-29 - Andrey Galkin<ul>
<li>Added .sync() API &amp; protocol</li>
<li>Added .waitExternal()</li>
<li>Added Mutex class</li>
<li>Added Throttle class</li>
</ul>
</li>
<li>v1.7 - 2015-06-01<ul>
<li>Removed .utils() artifact</li>
<li>Added 1.10 "Reserved keyword name clash"</li>
</ul>
</li>
<li>v1.6 - 2015-01-02<ul>
<li>Added last_exception state variable</li>
</ul>
</li>
<li>v1.5 - 2014-12-09<ul>
<li>Added concept of implicit as.success()</li>
<li>Deprecated as.successStep()</li>
<li>Updated examples</li>
<li>Updated "The Safety Rules of libraries with AsyncSteps interface"</li>
</ul>
</li>
<li>v1.4 - 2014-12-09<ul>
<li>Updated 1.6.1 and renamed to "The Safety Rules of AsyncSteps helpers"</li>
<li>Added 1.8 "Async Loops" and extended interface</li>
</ul>
</li>
<li>v1.3 - 2014-10-18<ul>
<li>Documented existing any way as.cancel()</li>
<li>Split AsyncSteps API in logical groups for better understanding</li>
</ul>
</li>
<li>v1.2 - 2014-09-30<ul>
<li>Added concept of successStep()</li>
<li>Added "error_info" convention</li>
<li>Changed behavior of as.error() to throw exception (not backward-compatible, but more like a bugfix)</li>
</ul>
</li>
<li>v1.1 - 2014-09-07<ul>
<li>Added cloning concept and requirements</li>
</ul>
</li>
<li>v1.0 - 2014-08-31</li>
</ul>
<h1>1. Concept</h1>
<p>This interface was born as a secondary option for
executor concept. However, it quickly became clear that
async/reactor/proactor/light threads/etc. should be base
for scalable high performance server implementations, even though it is more difficult for understanding and/or debugging.
Traditional synchronous program flow becomes an addon
on top of asynchronous base for legacy code and/or too
complex logic.</p>
<p>Program flow is split into non-blocking execution steps, represented
with execution callback function. Processing Unit (eg. CPU) halting/
spinning/switching-to-another-task is seen as a blocking action in program flow.</p>
<p>Any step must not call any of blocking functions, except for synchronization
with guaranteed minimal period of lock acquisition.
<em>Note: under minimal period, it is assumed that any acquired lock is 
immediately released after action with O(1) complexity and no delay
caused by programmatic suspension/locking of executing task</em></p>
<p>Every step is executed sequentially. Success result of any step
becomes input for the following step.</p>
<p>Each step can have own error handler. Error handler is called, if
AsyncSteps.error() is called within step execution or any of its 
sub-steps. Typical behavior is to ignore error and continue or
to make cleanup actions and complete job with error.</p>
<p>Each step can have own sequence of sub-steps. Sub-steps can be added
only during that step execution. Sub-step sequence is executed after
current step execution is finished.</p>
<p>If there are any sub-steps added then current step must not call
AsyncSteps.success() or AsyncSteps.error(). Otherwise, InternalError
is raised.</p>
<p>It is possible to create a special "parallel" sub-step and add
independent sub-steps to it. Execution of each parallel sub-step
is started all together. Parallel step completes with success
when all sub-steps complete with success. If error is raised in
any sub-step of parallel step then all other sub-steps are canceled.</p>
<p>Out-of-order cancel of execution can occur by timeout, 
execution control engine decision (e.g. Invoker disconnect) or
failure of sibling parallel step. Each step can install custom
on-cancel handler to free resources and/or cancel external jobs.
After cancel, it must be safe to destroy AsyncSteps object.</p>
<p>AsyncSteps must be used in Executor request processing. The same 
[root] AsyncSteps object must be used for all asynchronous tasks within
given request processing.</p>
<p>AsyncSteps may be used by Invoker implementation.</p>
<p>AsyncSteps must support derived classes in implementation-defined way.
Typical use case: functionality extension (e.g. request processing API).</p>
<p>For performance reasons, it is not economical to initialize AsyncSteps
with business logic every time. Every implementation must support
platform-specific AsyncSteps cloning/duplicating.</p>
<h2>1.1. Levels</h2>
<p>When AsyncSteps (or derived) object is created all steps are added
sequentially in Level 0 through add() and/or parallel(). Note: each
parallel() is seen as a step.</p>
<p>After AsyncSteps execution is initiated, each step of Level 0 is executed.
All sub-steps are added in Level n+1. Example:</p>
<pre><code>add() -&gt; Level 0 #1
    add() -&gt; Level 1 #1
        add() -&gt; Level 2 #1
        parallel() -&gt; Level 2 #2
        add() -&gt; Level 2 #3
    parallel() -&gt; Level 1 #2
    add() -&gt; Level 1 #3
parallel() -&gt; Level 0 #2
add() -&gt; Level 0 #3
</code></pre>
<p>Execution cannot continue to the next step of current Level until all steps of higher Level
are executed.</p>
<p>The execution sequence would be:</p>
<pre><code>Level 0 add #1
Level 1 add #1
Level 2 add #1
Level 2 parallel #2
Level 2 add #3
Level 1 parallel #2
Level 1 add #3
Level 0 parallel #2
Level 0 add #3
</code></pre>
<h2>1.2. Error handling</h2>
<p>Due to not linear programming, classic try/catch blocks are converted into execute/onerror.
Each added step may have custom error handler. If error handler is not specified then
control passed to lower Level error handler. If non is defined then execution is aborted.</p>
<p>Example:</p>
<pre><code>add( -&gt; Level 0
    func( as ){
        print( "Level 0 func" )
        add( -&gt; Level 1
            func( as ){
                print( "Level 1 func" )
                as.error( "myerror" )
            },
            onerror( as, error ){
                print( "Level 1 onerror: " + error )
                as.error( "newerror" )
            }
        )
    },
    onerror( as, error ){
        print( "Level 0 onerror: " + error )
        as.success( "Prm" )
    }
)
add( -&gt; Level 0
    func( as, param ){
        print( "Level 0 func2: " + param )
        as.success()
    }
)
</code></pre>
<p>Output would be:</p>
<pre><code>Level 0 func
Level 1 func
Level 1 onerror: myerror
Level 0 onerror: newerror
Level 0 func2: Prm
</code></pre>
<p>In synchronous way, it would look like:</p>
<pre><code>variable = null

try
{
    print( "Level 0 func" )

    try
    {
        print( "Level 1 func" )
        throw "myerror"
    }
    catch ( error )
    {
        print( "Level 1 onerror: " + error )
        throw "newerror"
    }
}
catch( error )
{
    print( "Level 0 onerror: " + error )
    variable = "Prm"
}

print( "Level 0 func2: " + variable )
</code></pre>
<h2>1.2.1. Steps in error handler</h2>
<p>Very often, error handler creates an alternative complex program path which
requires own async operation. Therefore, error handler must accept <code>as.add()</code>
as implicit <code>as.success()</code>.</p>
<p>If steps are added inside error handler they must remain on the same async stack
level while error handler itself gets removed.</p>
<p>Example:</p>
<pre><code>add( -&gt; Level 0
    func( as ){
        print( "Level 0 func" )
        add( -&gt; Level 1
            func( as ){
                print( "Level 1 func" )
                as.error( "first" )
            },
            onerror( as, error ){
                print( "Level 1 onerror: " + error )
                as.add( -&gt; Level 2
                    func() {
                        print( "Level 2 func" )
                        as.error( "second" );
                    },
                    onerror( as, error ) {
                        print( "Level 2 onerror: " + error )
                    }
                )
            }
        )
    },
    onerror( as, error ){
        print( "Level 0 onerror: " + error )
    }
)
</code></pre>
<p>Output would be:</p>
<pre><code>Level 0 func
Level 1 func
Level 1 onerror: first
Level 2 func
Level 2 onerror: second
Level 0 onerror: second
</code></pre>
<p><em>Note: "Level 1 onerror" is not executed second time!</em></p>
<h2>1.3. Wait for external resources</h2>
<p>Very often, execution of step cannot continue without waiting for external event like input from network or disk.
It is forbidden to block execution in event waiting. As a solution, there are special setTimeout() and setCancel()
methods.</p>
<p>Example:</p>
<pre><code>add(
    func( as ){
        socket.read( function( data ){
            as.success( data )
        } )

        as.setCancel( function(){
            socket.cancel_read()
        } )

        as.setTimeout( 30_000 ) // 30 seconds
    },
    onerror( as, error ){
        if ( error == timeout ) {
            print( "Timeout" )
        }
        else
        {
            print( "Read Error" )
        }
    }
)
</code></pre>
<h2>1.4. Parallel execution abort</h2>
<p>Definition of parallel steps makes no sense to continue execution if any of steps fails. To avoid
excessive time and resources spent on other steps, there is a concept of canceling execution similar to 
timeout above.</p>
<p>Example:</p>
<pre><code>as.parallel()
    .add(
        func( as ){
            as.setCancel( function(){ ... } )

            // do parallel job #1
            as.state()-&gt;result1 = ...;
        }
    )
    .add(
        func( as ){
            as.setCancel( function(){ ... } )

            // do parallel job #1
            as.state()-&gt;result2 = ...;
        }
    )
    .add(
        func( as ){
            as.error( "Some Error" )
        }
    )
as.add(
    func( as ){
        print( as.state()-&gt;result1 + as.state-&gt;result2 )
        as.success()
    }
)
</code></pre>
<h2>1.5. AsyncSteps cloning</h2>
<p>In long living applications the same business logic may be re-used multiple times
during execution.</p>
<p>In a REST API server example, complex business logic can be defined only once and
stored in a kind of AsyncSteps object repository.
On each request, a reference object from the repository would be copied for actual
processing with minimal overhead.</p>
<p>However, there would be no performance difference in sub-step definition unless
its callback function is also created at initialization time, but not at parent
step execution time (the default concept). So, it should be possible to predefine
those as well and copy/inherit during step execution. Copying steps must also
involve copying of state variables.</p>
<p>Example:</p>
<pre><code>AsyncSteps req_repo_common;
req_repo_common.add(func( as ){
    as.add( func( as ){ ... } );
    as.copyFrom( as.state().business_logic );
    as.add( func( as ){ ... } );
});

AsyncSteps req_repo_buslog1;
req_repo_buslog1
    .add(func( as ){ ... })
    .add(func( as ){ ... });

AsyncSteps actual_exec = copy req_repo_common;
actual_exec.state().business_logic = req_repo_buslog1;
actual_exec.execute();
</code></pre>
<p>However, this approach only make sense for deep performance optimizations.</p>
<h2>1.6. Implicit as.success()</h2>
<p>If there are no sub-steps added, no timeout set and no cancel handler set then
implicit as.success() call is assumed to simplify code and increase efficiency.</p>
<pre><code>as.add(func( as ){
    doSomeStuff( as );
})
</code></pre>
<p>As in many cases it's required to wait for external event without any additional
conditions, the general approach used to be adding an empty cancel handler. To
avoid that, an explicit <code>.waitExternal()</code> API is available.</p>
<h2>1.7. Error Info, Last Exception and Async Call Stack</h2>
<p>Pre-defined state variables:</p>
<ul>
<li><strong>error_info</strong> - value of the second parameter passed to the last <em>as.error()</em> call</li>
<li><strong>last_exception</strong> - the last exception caught, if feasible</li>
<li><strong>async_stack</strong> - implementation-defined stack of step handler references</li>
</ul>
<p>Error code is not always descriptive enough, especially, if it can be generated in multiple ways.
As a convention special "error_info" state field should hold descriptive information of the last error.
Therefore, <em>as.error()</em> is extended with optional parameter error_info.</p>
<p>"last_exception" state variables may hold the last exception object caught, if feasible
to implement. It should be populated with FutoIn errors as well.</p>
<h2>1.8. Async Loops</h2>
<p>Almost always, async program flow is not linear. Sometimes, loops are required.</p>
<p>Basic principals of async loops:</p>
<pre><code>    as.loop( func( as ){
        call_some_library( as );
        as.add( func( as, result ){
            if ( !result )
            {
                // exit loop
                as.break();
            }
        } );
    } )
</code></pre>
<p>Inner loops and identifiers:</p>
<pre><code>    // start loop
    as.loop( 
        func( as ){
            as.loop( func( as ){
                call_some_library( as );
                as.add( func( as, result ){
                    if ( !result )
                    {
                        // exit loop
                        as.continue( "OUTER" );
                    }

                    as.success( result );
                } );
            } );

            as.add( func( as, result ){
                // use it somehow
                as.success();
            } );
        },
        "OUTER"
    )
</code></pre>
<p>Loop n times.</p>
<pre><code>    as.repeat( 3, func( as, i ){
        print( 'Iteration: ' + i )
    } )
</code></pre>
<p>Traverse through list or map:</p>
<pre><code>    as.forEach(
        [ 'apple', 'banana' ],
        func( as, k, v ){
            print( k + " = " + v )
        }
    )
</code></pre>
<h3>1.8.1. Termination</h3>
<p>Normal loop termination is performed either by loop condition (e.g. as.forEach(), as.repeat())
or by as.break() call. Normal termination is seen as as.success() call.</p>
<p>Abnormal termination is possible through as.error(), including timeout, or external as.cancel().
Abnormal termination is seen as as.error() call.</p>
<h2>1.9. The Safety Rules of libraries with AsyncSteps interface</h2>
<ol>
<li>as.success() should be called only in top-most function of the
    step (the one passed to as.add() directly)</li>
<li>setCancel() and/or setTimeout() must be called only in top most function
    as repeated call overrides in scope of step</li>
</ol>
<h2>1.10. Reserved keyword name clash</h2>
<p>If any of API identifiers clashes with reserved word or has illegal symbols then
implementation-defined name mangling is allowed, but with the following guidelines
in priority.</p>
<p>Pre-defined alternative method names, if the default matches language-specific reserved keywords:</p>
<ul>
<li><em>loop</em> -&gt; makeLoop</li>
<li><em>forEach</em> -&gt; loopForEach</li>
<li><em>repeat</em> -&gt; repeatLoop</li>
<li><em>break</em> -&gt; breakLoop</li>
<li><em>continue</em> -&gt; continueLoop</li>
<li>Otherwise, - try adding underscore to the end of the
    identifier (e.g. do -&gt; do_)</li>
</ul>
<h2>1.11. Synchronization</h2>
<h3>1.11.1. Mutual exclusion</h3>
<p>As with any multi-threaded application, multi-step cases may also require synchronization
to ensure not more than N steps enter the same critical section.</p>
<p>Implemented as <code>Mutex</code> class.</p>
<h3>1.11.2. Throttling</h3>
<p>For general stability reasons and protection of self-DoS, it may be required to limit
number of steps allowed to enter critical section within time period.</p>
<p>Implemented as <code>Throttle</code> class.</p>
<h3>1.11.3. API details</h3>
<p>A special <code>.sync(obj, step, err_handler)</code> API is available to synchronize against
any object supporting synchronization protocol <code>.sync(as, step, err_handler)</code>.</p>
<p>Synchronization object is allowed to add own steps and is responsible for adding
request steps under protection of provided synchronization. Synchronization object
must correctly handle canceled execution and possible errors.</p>
<p>Incoming success parameters must be passed to critical section step.
Resulting success parameters must be forwarded to the following steps like there is
no critical section logic.</p>
<h3>1.11.4. Re-entrancy requirements</h3>
<p>All synchronization implementations must either allow multiple re-entrancy of the
same AsyncSteps instance or properly detect and raise error on such event.</p>
<p>All implementations must correctly detect parallel flows in scope of single AsyncSteps
instance and treat each as separate one. None of paralleled steps should inherit
lock state of parent step.</p>
<h3>1.11.5. Deadlock detection</h3>
<p>Deadlock detection is optional and is not mandatory required.</p>
<h3>1.11.6. Max queue limits</h3>
<p>It may be required to limit maximum number of pending AsyncSteps flows. If overall
queue limit is reached then new entries must get "DefenseRejected" error.</p>
<h3>1.11.7. Processing limits</h3>
<p>Request processing stability requires to limit both simultaneous connections and
request rate. Therefore a special synchronization primitive <code>Limiter</code> wrapping
<code>Mutex</code> and <code>Throttle</code> is introduced to impose limits in scope.</p>
<h3>1.12. Success step and result injection</h3>
<p>Sometimes, it's required to return a value after inner step are executed. It leads
to code like:</p>
<p><code>value = 123;
    as.add( subStep() );
    as.add( (as) =&gt; as.success( value ) );</code></p>
<p>To optimize and make the code cleaner previously deprecated <code>successStep()</code> is
returned. Example:</p>
<p><code>value = 123;
    as.add( subStep() );
    as.successStep( value );</code></p>
<h3>1.13. Promise/await integration</h3>
<p>As Promises and <code>await</code> patterns become more and more popular in modern technologies,
AsyncSteps should support them through <code>as.await(future_or_promise)</code> call.</p>
<p>Details of implementation is specific to particular technology. However, the following
guidelines should be used:</p>
<ol>
<li>Async step must be added.</li>
<li>If <code>future_or_promise</code> is cancellable then <code>as.setCancel()</code> must be used.</li>
<li>Otherwise, <code>as.waitExternal()</code> to be used.</li>
<li>Errors must be propagated through <code>as.error()</code></li>
<li>Result must be propagated through <code>as.success()</code></li>
</ol>
<h1>2. Async Steps API</h1>
<h2>2.1. Types</h2>
<ul>
<li><code>void execute_callback( AsyncSteps as[, previous_success_args] )</code><ul>
<li>first argument is always AsyncSteps object</li>
<li>other arguments come from the previous as.success() call, if any</li>
<li>returns nothing</li>
<li>behavior:<ul>
<li>either set completion status through <code>as.success()</code> or <code>as.error()</code></li>
<li>or add sub-steps through <code>as.add()</code> and/or <code>as.parallel()</code></li>
<li>Optionally, set set time limit through <code>as.setTimeout()</code> and/or
    set cancel handler through <code>as.setCancel()</code></li>
<li>any violation is reported as <code>as.error( InternalError )</code>. Not
    applicable to implicit success.</li>
</ul>
</li>
<li>can use <code>as.state()</code> for global current job state data</li>
</ul>
</li>
<li><code>void error_callback( AsyncSteps as, error )</code><ul>
<li>the first argument is always AsyncSteps object</li>
<li>the second argument comes from the previous <code>as.error()</code> call</li>
<li>returns nothing</li>
<li>behavior, completes through:<ul>
<li><code>as.success()</code> - continue execution from the next step, after return</li>
<li><code>as.error()</code> - change error string</li>
<li>return - continue unwinding error handler stack</li>
<li>any violation is reported as <code>as.error( InternalError )</code></li>
</ul>
</li>
<li>can use as.state() for global current job state data</li>
</ul>
</li>
<li><code>void cancel_callback( AsyncSteps as )</code><ul>
<li>it must be used to cancel out of AsyncSteps program flow actions, like
    waiting on connection, timer, dedicated task, etc.</li>
</ul>
</li>
<li><code>interface ISync</code><ul>
<li><code>void sync( AsyncSteps, execute_callback[, error_callback] )</code><ul>
<li>synchronized independent or parallel AsyncSteps, execute provided
    callbacks in critical section.</li>
</ul>
</li>
</ul>
</li>
</ul>
<h2>2.2. Functions</h2>
<p>It is assumed that all functions in this section are part of <strong>single AsyncSteps interface</strong>.
However, they are grouped by semantical scope of use.</p>
<h3>2.2.1. Common API - can be used in any context</h3>
<ol>
<li><code>AsyncSteps add( execute_callback func[, error_callback onerror] )</code><ul>
<li>add step, executor callback gets async interface as parameter</li>
<li>can be called multiple times to add sub-steps of the same level (sequential execution)</li>
<li>steps are queued in the same execution level (sub-steps create a new level)</li>
<li>returns current level AsyncSteps object accessor</li>
</ul>
</li>
<li><code>AsyncSteps parallel( [error_callback onerror] )</code><ul>
<li>creates a step and returns specialization of AsyncSteps interface<ul>
<li>all add()'ed sub-steps are executed in parallel (not strictly required)</li>
<li>the next step in current level is executed only when all parallel steps complete</li>
<li>sub-steps of parallel steps follow normal sequential semantics</li>
<li><code>success()</code> does not allow any arguments - use <code>state()</code> to pass results</li>
</ul>
</li>
</ul>
</li>
<li><code>Map state()</code><ul>
<li>returns reference to map/object, which can be populated with arbitrary state values</li>
</ul>
</li>
<li><em>get/set/exists/unset</em> wildcard accessor, which map to state() variables<ul>
<li>only if supported by language/platform</li>
</ul>
</li>
<li><code>AsyncSteps copyFrom( AsyncSteps other )</code><ul>
<li>Copy steps and state variables not present in current state
from other(model) AsyncSteps object</li>
<li>See cloning concept</li>
</ul>
</li>
<li><em>clone</em>/<em>copy c-tor</em><ul>
<li>implementation-defined way of cloning AsyncSteps object</li>
</ul>
</li>
<li><code>AsyncSteps sync(ISync obj, execute_callback func[, error_callback onerror] )</code><ul>
<li>add step synchronized against obj</li>
</ul>
</li>
<li><code>AsyncSteps successStep( [result_arg, ...] )</code><ul>
<li>shortcut for <code>as.add( (as) =&gt; as.success( result_arg, ... ) )</code></li>
</ul>
</li>
<li><code>AsyncSteps await( future_or_promise[, error_callback onerror] )</code><ul>
<li>integrate technology-specific Future/Promise as a step</li>
</ul>
</li>
</ol>
<h3>2.2.2. Execution API - can be used only inside execute_callback</h3>
<p><em>Note: <code>success()</code> and <code>error()</code> can be used in error_callback as well</em></p>
<ol>
<li><code>void success( [result_arg, ...] )</code><ul>
<li>successfully complete current step execution. Should be called from func()</li>
</ul>
</li>
<li><code>void error( name [, error_info] )</code><ul>
<li>complete with error</li>
<li>throws <code>FutoIn.Error</code> exception</li>
<li>calls <code>onerror( async_iface, name )</code> after returning to execution engine</li>
<li><code>error_info</code>- assigned to "error_info" state field</li>
</ul>
</li>
<li><code>void setTimeout( timeout_ms )</code><ul>
<li>inform execution engine to wait for either success() or error()
for specified timeout in ms. On timeout, error("Timeout") is called</li>
</ul>
</li>
<li><code>call operator overloading</code><ul>
<li>if supported by language/platform, alias for success()</li>
</ul>
</li>
<li><code>void setCancel( cancel_callback oncancel )</code><ul>
<li>set callback, to be used to cancel execution</li>
</ul>
</li>
<li><code>void waitExternal()</code><ul>
<li>prevent implicit <code>as.success()</code> behavior of current step</li>
</ul>
</li>
</ol>
<h3>2.2.3. Control API - can be used only on Root AsyncSteps object</h3>
<ol>
<li><code>execute()</code> - must be called only once after root object steps are configured.<ul>
<li>Initiates AsyncSteps execution implementation-defined way</li>
</ul>
</li>
<li><code>cancel()</code> - may be called on root object to asynchronously cancel execution</li>
</ol>
<h3>2.2.4. Execution Loop API - can be used only inside <code>execute_callback</code></h3>
<ol>
<li><code>void loop( func, [, label] )</code><ul>
<li>execute loop until <code>as.break()</code> is called</li>
<li><code>func( as )</code> - loop body</li>
<li><code>label</code> - optional label to use for <code>as.break()</code> and <code>as.continue()</code> in inner loops</li>
</ul>
</li>
<li><code>void forEach( map|list, func [, label] )</code><ul>
<li>for each <code>map</code> or <code>list</code> element call <code>func( as, key, value )</code></li>
<li><code>func( as, key, value )</code> - loop body</li>
<li><code>label</code> - optional label to use for <code>as.break()</code> and <code>as.continue()</code> in inner loops</li>
</ul>
</li>
<li><code>void repeat( count, func [, label] )</code><ul>
<li>Call <code>func(as, i)</code> for <code>count</code> times</li>
<li><code>count</code> - how many times to call the <code>func</code></li>
<li><code>func( as, i )</code> - loop body, i - current iteration starting from 0</li>
<li><code>label</code> - optional label to use for <code>as.break()</code> and <code>as.continue()</code> in inner loops</li>
</ul>
</li>
<li><code>void break( [label] )</code><ul>
<li>break execution of current loop, throws exception</li>
<li><code>label</code> - unwind loops, until <code>label</code> named loop is exited</li>
</ul>
</li>
<li><code>void continue( [label] )</code><ul>
<li>continue loop execution from the next iteration, throws exception</li>
<li><code>label</code> - break loops, until <code>label</code> named loop is found</li>
</ul>
</li>
</ol>
<h3>2.3. <code>Mutex</code> class</h3>
<ul>
<li>Must implemenet <code>ISync</code> interface</li>
<li>Functions:<ul>
<li><code>c-tor(unsigned integer max=1, unsigned integer max_queue=null)</code><ul>
<li>set maximum number of parallel AsyncSteps entering critical section</li>
<li><code>max_queue</code> - optionally, limit queue length</li>
</ul>
</li>
</ul>
</li>
</ul>
<h3>2.4. <code>Throttle</code> class</h3>
<ul>
<li>Must implemenet <code>ISync</code> interface</li>
<li>Functions:<ul>
<li><code>c-tor(unsigned integer max, unsigned integer period_ms=1000, unsigned integer max_queue=null)</code><ul>
<li>set maximum number of critical section entries within specification time period.</li>
<li><code>period_ms</code> - time period in milliseconds</li>
<li><code>max_queue</code> - optionally, limit queue length</li>
</ul>
</li>
</ul>
</li>
</ul>
<h3>2.5. <code>Limiter</code> class</h3>
<ul>
<li>Must implemenet <code>ISync</code> interface</li>
<li>Functions:<ul>
<li><code>c-tor(options)</code><ul>
<li>Complex limit handling</li>
<li><code>options.concurrent=1</code>  - maximum concurrent flows</li>
<li><code>options.max_queue=0</code> - maximum queued</li>
<li><code>options.rate=1</code>  - maximum entries in period</li>
<li><code>options.period_ms=1000</code>  - period length</li>
<li><code>options.burst=0</code>  - maximum queue for rate limiting</li>
</ul>
</li>
</ul>
</li>
</ul>
<h1>3. Examples</h1>
<p>In pseudo-code.</p>
<h2>3.1. Single-level steps</h2>
<pre><code>AsyncStepsImpl as;

as.add(
    function( inner_as ){
        if ( something )
            inner_as.success( 1, 2 )
        else
            inner_as.error( NotImplemented )
    },
    function( inner_as, error ){
        externalError( error );
    }
).add(
    function( inner_as, res1, res2 ){
        externalSuccess( res1, res2 );
    },
)
</code></pre>
<h2>3.2. Sub-steps</h2>
<pre><code>AsyncStepsImpl as;

as.add(
    function( inner_as ){
        inner_as.add(
            function( inner2_as ){
                if ( something )
                    inner2_as.success( 1 )
                else
                    inner2_as.error( NotImplemented )
            },
            function( inner2_as, error )
            {
                log( "Spotted error " + error )
                // continue with higher level error handlers
            }
        )
        inner_as.add(
            function( inner2_as, res1 ){
                inner2_as.success( res1, 2 )
            }
        )
    },
    function( inner_as, error ){
        externalError( error );
    }
).add(
    function( inner_as, res1, res2 ){
        externalSuccess( res1, res2 );
    },
)
</code></pre>
<h2>3.3. parallel() steps and state()</h2>
<pre><code>AsyncStepsImpl as;

as.add(
    function( inner_as ){
        inner_as.parallel().add(
            function( inner2_as ){
                inner2_as.state().parallel_1 = 1;
            },
            function( inner2_as, error )
            {
                log( "Spotted error " + error )
                // continue with higher level error handlers
            }
        ).add(
            function( inner2_as ){
                inner2_as.state().parallel_2 = 2;
            },
            function( inner2_as, error )
            {
                inner2_as.state().parallel_2 = 0;
                // ignore error
            }
        )
    },
    function( inner_as, error ){
        externalError( error );
    }
).add(
    function( inner_as, res1, res2 ){
        externalSuccess(
            as.state().parallel_1,
            as.state().parallel_2
        );
    },
)
</code></pre>
<h2>3.4. loops</h2>
<pre><code>AsyncStepsImpl as;

as.add(
    function( as ){
        as.repeat( 3, function( as, i ) {
            print i;
        } );

        as.forEach( [ 1, 3, 3 ], function( as, k, v ) {
            print k "=" v;
        } );

        as.forEach( as.state(), function( as, k, v ) {
            print k "=" v;
        } );
    },
)
</code></pre>
<h2>3.5. External event wait</h2>
<pre><code>AsyncStepsImpl as;

as.add(
    function( as ){
        as.waitExternal();

        callSomeExternal( function(err) {
            if (err)
            {
                try {
                    as.error(err);
                } catch {
                    // ignore
                }
            }
            else
            {
                as.success();
            }
        } );
    },
)
</code></pre>
<h2>3.6. Synchronization</h2>
<pre><code>AsyncStepsImpl as;
MutexImpl mutex(10);

as.sync(
    mutex,
    function( as ){
        // critical section with regular AsyncSteps
    },
)
</code></pre>
<p>=END OF SPEC=</p>
</body></html>